FROM python:3.8.8-slim-buster

# Copy files to current directory:
COPY . /app/
WORKDIR /app/

# Install luigi:
RUN pip install --upgrade pip && pip install -r requirements.txt

# Set env variables:
ENV PYTHONPATH /app/
ENV LUIGI_CONFIG_PATH /app/luigi.cfg
ENV KUBECONFIG /app/.kube/config

# Create path for pickle state file:
RUN mkdir /var/lib/gce-drive