apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: luigi-scheduler-db-replication-job
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      parallelism: 1
      template:
        metadata:
          labels:
            app: luigi-scheduler
        spec:
          containers:
          - name: luigi-scheduler
            resources:
              limits:
                memory: 512Mi
                cpu: 250m
              requests:
                cpu: 250m
                memory: 512Mi
            image: us-central1-docker.pkg.dev/analytics-and-insights-311921/luigi-assets/luigi-scheduler-db-replication-job:v1.0.0
            imagePullPolicy: Always
            command: ["python3"]
            args: ["main.py"]
          restartPolicy: Never
      backoffLimit: 1
